version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: pulse_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: pulse_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pulse
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./server/public:/app/public
      - uploads_data:/app/uploads

volumes:
  mongo_data:
  uploads_data:
